language: python
python:
  - 2.6
  - 2.7

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
  - python run_tests_all_pytz.py --download-only

script:
  - python run_tests_all_pytz.py

after_success:
  - pip install coveralls
  - coverage run --source=datetime_tz setup.py test
  - coveralls
