language: python
python:
  - 2.6
  - 2.7

install:
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install

script:
  - python run_tests_all_pytz.py

after_success:
  - pip install coveralls --use-mirrors
  - coverage run --source=datetime_tz setup.py test
  - coveralls
